services:
  api:
    build:
      context: .
      target: development
    command: npm run start:dev
    restart: unless-stopped
    hostname: api
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "3110:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    restart: always
    hostname: postgres
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - backend
    volumes:
      - redis_data:/data

networks:
  backend:

volumes:
  postgres_data:
  redis_data: